#include <fstream>
#include <cassert>
#include "Render.h"
using namespace retro;
void save(GFXcanvas1& c,const char* name){std::ofstream f(std::string("previews/")+name+".pbm",std::ios::binary);f<<"P4\n800 480\n";for(int i=0;i<48000;i++){unsigned char b=~c.getBuffer()[i];f.write((char*)&b,1);}}
int main(){
 setenv("TZ","EST5EDT,M3.2.0,M11.1.0",1);tzset();GFXcanvas1 c(800,480);Renderer r(c);assert(c.width()==480 && c.height()==800);assert(findLogo(0,"10") && findLogo(1,"17") && findLogo(2,"2") && findLogo(3,"333"));assert(!findLogo(0,"missing"));UI u;u.now=isoEpoch("2026-09-29T23:42Z");u.clockValid=true;u.online=true;u.date="20260929";
 {Game h1;h1.id="h1";h1.start="2026-09-29T23:15Z";h1.state="post";h1.status="Final";h1.away={"3","Chicago Bears","CHI","24"};h1.home={"8","Detroit Lions","DET","31"};
  Game h2;h2.id="h2";h2.start="2026-09-29T22:00Z";h2.state="in";h2.status="Top 7th";h2.away={"10","New York Yankees","NYY","4"};h2.home={"2","Boston Red Sox","BOS","2"};
  u.recent={{1,h1},{0,h2}};u.selected=7;r.render(u);save(c,"home");u.tab=1;u.recent={{0,h2}};u.selected=1;r.render(u);save(c,"home-mlb-demo");u.tab=0;u.selected=0;u.recent.clear();}
 // Explicit synthetic fixtures for visual review only, never bundled in firmware.
 u.snapshot={0,u.date,u.now,{}};Game g;g.id="preview";g.start="2026-09-29T23:05Z";g.away={"10","New York Yankees","NYY","4"};g.home={"2","Boston Red Sox","BOS","2"};g.state="in";g.status="Top 7th";u.snapshot.games.push_back(g);u.page=Page::Games;u.selected=1;r.render(u);save(c,"games-demo");
 {UI f=u;f.feed=true;f.league=1;f.snapshot.league=1;f.snapshot.span=14;f.snapshot.games.clear();
  Game a;a.id="p1";a.start="2026-09-29T23:15Z";a.state="in";a.status="3rd Qtr";a.away={"12","Kansas City Chiefs","KC","17"};a.home={"17","New England Patriots","NE","14"};
  Game b;b.id="p2";b.start="2026-09-27T20:25Z";b.state="post";b.status="Final";b.away={"3","Chicago Bears","CHI","24"};b.home={"8","Detroit Lions","DET","31"};
  Game d;d.id="p3";d.start="2026-09-20T17:00Z";d.state="post";d.status="Final/OT";d.away={"10","Tennessee Titans","TEN","20"};d.home={"34","Houston Texans","HOU","23"};
  Game e;e.id="p4";e.start="2026-10-01T00:15Z";e.state="pre";e.status="Scheduled";e.away={"25","San Francisco 49ers","SF","0"};e.home={"22","Arizona Cardinals","ARI","0"};
  e.week=4;a.week=4;b.week=3;d.week=2;for(Game* w:{&e,&a,&b,&d})w->seasonType=2;
  f.snapshot.games={e,a,b};for(int i=0;i<8;i++){Game x=i%2?b:d;x.id="q"+std::to_string(i);x.start=i%2?"2026-09-27T17:00Z":"2026-09-20T20:25Z";f.snapshot.games.push_back(x);}
  std::stable_sort(f.snapshot.games.begin(),f.snapshot.games.end(),[](const Game& x,const Game& y){return isoEpoch(x.start)>isoEpoch(y.start);});
  f.selected=3;r.render(f);save(c,"games-feed-demo");f.selected=11;r.render(f);save(c,"games-feed-page2-demo");
  UI tp=f;tp.filter="12";tp.filterName="Kansas City Chiefs";tp.favorites={{1,"12","Kansas City Chiefs"}};tp.snapshot.team="12";tp.snapshot.games={e,a};tp.selected=0;r.render(tp);save(c,"team-demo");}
 for(int i=0;i<5;i++)u.snapshot.games.push_back(g);u.selected=3;r.render(u);save(c,"games-full-demo");u.selected=4;r.render(u);save(c,"games-page2-demo");{UI n=u;n.league=1;n.page=Page::Detail;n.selected=1;Game x;x.id="nfl";x.start="2026-09-27T17:00Z";x.state="post";x.status="Final";x.away={"24","Los Angeles Chargers","LAC","16"};x.home={"2","Buffalo Bills","BUF","24"};x.venue="Highmark Stadium";n.snapshot.games={x};n.gameIndex=0;
  n.detail.id="nfl";n.detail.awayRecord="0-3";n.detail.homeRecord="3-0";n.detail.awayLine={10,0,3,3};n.detail.homeLine={0,10,0,14};
  n.detail.stats={{"PASS","Herbert 226","Allen 204"},{"RUSH","Hampton 56","Cook III 154"},{"REC","Harris 76","Moore 67"},{"TOT YDS","348","350"},{"TURNOVR","1","5"}};n.detail.headline="Allen, Bills outlast Chargers 24-16 despite committing 5 turnovers";r.render(n);save(c,"detail-nfl-demo");}
 u.detail.id="preview";u.detail.awayRecord="93-68";u.detail.homeRecord="90-71";u.detail.awayLine={0,1,0,0,0,1,0,2,0};u.detail.homeLine={0,0,0,0,2,0,0,0};u.detail.awayHits="7";u.detail.homeHits="6";u.detail.awayErrors="0";u.detail.homeErrors="1";
 u.detail.stats={{"HR","Judge 1-3 HR","Devers 2-4 HR"},{"RBI","Judge 3","Devers 2"},{"BATTING","Soto 3-3","Story 2-4"}};u.detail.headline="Judge homers twice as Yankees hold off Red Sox 4-2 in the Bronx";
 u.page=Page::Detail;u.selected=2;r.render(u);save(c,"detail-demo");u.selected=0;u.online=false;u.offlineSince=u.now-5400;r.render(u);save(c,"offline-demo");u.page=Page::Games;r.render(u);save(c,"offline-games-demo");u.online=true;
 {UI b=u;b.page=Page::Launcher;b.selected=LAUNCH_TAB0;b.votd={43,3,16};std::ifstream jf("tests/fixtures/john3.txt");std::string text((std::istreambuf_iterator<char>(jf)),std::istreambuf_iterator<char>());
  auto verses=bibleVerses(text);b.votdText=verses[15];b.bible.book=43;b.bible.chapter=3;b.bible.pages=paginateBible(verses,readWidth,456,READ_LINES);b.bible.page=1;Game h1;h1.id="h1";h1.start="2026-09-29T23:15Z";h1.state="post";h1.status="Final";h1.away={"3","Chicago Bears","CHI","24"};h1.home={"8","Detroit Lions","DET","31"};Game h2;h2.id="h2";h2.start="2026-09-29T22:00Z";h2.state="in";h2.status="Top 7th";h2.away={"10","New York Yankees","NYY","4"};h2.home={"2","Boston Red Sox","BOS","2"};b.recent={{1,h1},{1,h1},{0,h2},{0,h2},{0,h2}};b.weather.valid=true;b.weather.temp=62;b.weather.high=65;b.weather.low=59;b.weather.rain=92;b.weather.code=61;b.weather.day=true;b.weather.city="Williamsburg";b.battery=73;r.render(b);save(c,"launcher-demo");{std::ifstream wf("tests/fixtures/weather.json");JsonDocument full;deserializeJson(full,wf);UI wu=b;wu.weather.city="Painesville";decodeWeather(full,wu.now,wu.weather);wu.page=Page::Weather;r.render(wu);save(c,"weather-demo");wu.page=Page::Launcher;wu.selected=LAUNCH_WEATHER;r.render(wu);save(c,"launcher-weather-demo");}b.selected=LAUNCH_BIBLE;r.render(b);save(c,"launcher-bible-demo");b.page=Page::BibleHome;b.selected=0;r.render(b);save(c,"bible-home-demo");
  b.page=Page::Bible;b.bible.page=biblePageOf(b.bible.pages,16);b.bible.verse=16;r.render(b);save(c,"bible-reader-demo");b.bible.verse=0;b.bible.page=0;r.render(b);save(c,"bible-reader-page1-demo");
  b.page=Page::BibleBooks;b.bible.pick=42;r.render(b);save(c,"bible-books-demo");b.page=Page::BibleChapters;b.bible.pickBook=19;b.bible.pick=22;r.render(b);save(c,"bible-chapters-demo");
  r.sleepVerse(b);c.fillRect(0,0,480,52,0);c.setTextColor(1);c.setTextSize(2);c.setCursor(240-27*6,5);c.print("PRESS ANY BUTTON FOR LATEST");c.setCursor(240-31*6,28);c.print("ASLEEP - 1:42 PM - BATTERY 100%");save(c,"sleep-verse-demo");}
 {UI v=u;v.page=Page::Voice;v.voice=VoiceState::Answer;v.voiceHeard="who won the super bowl in nineteen eighty five";v.voiceAnswer="The Chicago Bears beat the New England Patriots 46-10 in Super Bowl XX, played in January 1986 for the 1985 season.";r.render(v);save(c,"voice-answer-demo");}
 {UI l=u;l.page=Page::Detail;l.selected=0;l.detail=GameDetail{};l.online=true;r.render(l);save(c,"detail-loading-demo");}
 {UI d=u;d.page=Page::Devotional;std::ifstream df("tests/fixtures/devotional.json");std::string fx((std::istreambuf_iterator<char>(df)),std::istreambuf_iterator<char>());JsonDocument wrap;wrap["choices"][0]["message"]["content"]=fx;parseDevotional(wrap,{19,119,9},"How can a young man keep his way pure? By guarding it according to Your word.",272,d.devotional);r.render(d);save(c,"devotional-demo");d.page=Page::BibleHome;d.selected=2;d.votd={19,119,9};d.votdText=d.devotional.verse;r.render(d);save(c,"bible-home-demo");}
 u.page=Page::Date;r.render(u);save(c,"date-demo");u.page=Page::Settings;r.render(u);save(c,"settings-demo");u.page=Page::Favorites;r.render(u);save(c,"favorites-empty-demo");u.favorites={{0,"10","New York Yankees"},{3,"333","Alabama Crimson Tide"}};r.render(u);save(c,"favorites-demo");u.page=Page::Games;u.snapshot.games.clear();r.render(u);save(c,"empty-demo");u.page=Page::Voice;r.render(u);save(c,"voice-demo");u.page=Page::Wifi;u.ap=true;u.apName="PixelLeague-734C";u.apPass="play12345678";u.notice="Setup stays open for 10 minutes.";r.render(u);save(c,"setup-demo");
}
