#!/usr/bin/env python3
"""Rasterize a TTF to an Adafruit GFX 1-bit font header; optionally render samples.

  build_font.py --size 12 --weight 500 --name InterSmall --out firmware/RetroSports/InterSmall.h
  build_font.py --size 20 --weight 500 --space 1 --name InterRead --out firmware/RetroSports/InterRead.h
  build_font.py --size 13 --weight 650 --name InterRow --out firmware/RetroSports/InterRow.h
  build_font.py --samples previews/font-samples.png 11:500 12:500 12:600 13:500
"""
import argparse, pathlib
from PIL import Image, ImageDraw, ImageFont
ROOT=pathlib.Path(__file__).resolve().parent.parent
TTF=ROOT/'assets/fonts/Inter-Variable.ttf'
SAMPLE=['SUN 9/27 FINAL   TODAY 3RD QTR 10:23','WED 9/30 8:15 PM   SAVED TOP 7TH','Empower Field at Mile High  2-1  93-68','SELECT A TEAM TO SEE ITS GAMES']
def load(size,weight):
 f=ImageFont.truetype(str(TTF),size);f.set_variation_by_axes([14,weight]);return f
def glyphs(font,space=0):
 out=[]
 for code in range(32,127):
  ch=chr(code);mask,(ox,oy)=font.getmask2(ch,mode='1',anchor='ls');w,h=mask.size
  adv=max(1,round(font.getlength(ch,mode='1')))
  if ch==' ':adv+=space
  bits=[]
  for y in range(h):
   for x in range(w):bits.append(1 if mask.getpixel((x,y)) else 0)
  if not any(bits):w=h=0;bits=[]
  out.append((code,w,h,adv,ox,oy,bits))
 return out
def header(name,size,weight,space=0):
 font=load(size,weight);gs=glyphs(font,space);data=[];table=[];offset=0
 for code,w,h,adv,ox,oy,bits in gs:
  table.append(f' {{{offset},{w},{h},{adv},{ox},{oy}}}, // {chr(code)!r}')
  packed=bytearray();acc=0;n=0
  for b in bits:
   acc=(acc<<1)|b;n+=1
   if n==8:packed.append(acc);acc=0;n=0
  if n:packed.append(acc<<(8-n))
  data.extend(packed);offset+=len(packed)
 ascent,descent=font.getmetrics();line=ascent+descent
 top=max((-oy for _,w,h,_,_,oy,_ in gs if h),default=0)
 return '\n'.join([f'// Generated by tools/build_font.py: Inter {weight} at {size} px, 1-bit. Inter is licensed under',
  '// the SIL Open Font License 1.1 (assets/fonts/OFL.txt).','#pragma once','#include <Adafruit_GFX.h>',
  f'static const uint8_t {name}Bitmaps[] PROGMEM = {{'+','.join(f'0x{b:02x}' for b in data)+'};',
  f'static const GFXglyph {name}Glyphs[] PROGMEM = {{']+table+['};',
  f'static const GFXfont {name} PROGMEM = {{(uint8_t*){name}Bitmaps,(GFXglyph*){name}Glyphs,32,126,{line}}};',
  f'static const int {name}Ascent={top}; // rows above the baseline used by the tallest glyph',
  f'static const int {name}Line={line};',''])
def samples(path,specs):
 rows=[];W=460
 for spec in specs:
  size,weight=(int(x) for x in spec.split(':'));font=load(size,weight);h=size+8
  im=Image.new('1',(W,h*len(SAMPLE)+12),1);d=ImageDraw.Draw(im);d.text((2,0),f'{size}px w{weight}',font=load(10,600),fill=0)
  for i,s in enumerate(SAMPLE):d.text((70 if i==0 else 2,12+i*h) if i==0 else (2,12+i*h),s,font=font,fill=0)
  rows.append(im)
 out=Image.new('1',(W,sum(r.height+6 for r in rows)),1);y=0
 for r in rows:out.paste(r,(0,y));y+=r.height+6
 out=out.resize((out.width*2,out.height*2),Image.Resampling.NEAREST);out.save(path);print('saved',path)
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--size',type=int,default=12);p.add_argument('--weight',type=int,default=500);p.add_argument('--name',default='InterSmall');p.add_argument('--out');p.add_argument('--space',type=int,default=0,help='extra pixels on the space glyph (reading text)');p.add_argument('--samples');p.add_argument('specs',nargs='*')
 a=p.parse_args()
 if a.samples:samples(a.samples,a.specs or ['11:500','12:500','12:600','13:500'])
 if a.out:pathlib.Path(a.out).write_text(header(a.name,a.size,a.weight,a.space));print('wrote',a.out)
