#!/usr/bin/env python3
"""Build offline 1-bit firmware assets from ESPN team artwork; keep provenance."""
import concurrent.futures, io, json, pathlib, urllib.request
from PIL import Image, ImageOps
ROOT=pathlib.Path(__file__).resolve().parent.parent
ASSETS=ROOT/'assets/logos'; CACHE=ASSETS/'source'; CACHE.mkdir(exist_ok=True)
def entries(node):
 for entry in node.get('standings',{}).get('entries',[]): yield entry['team']['id']
 for child in node.get('children',[]): yield from entries(child)
fbs=set(entries(json.loads((ASSETS/'cfb-standings.json').read_text())))
jobs=[]
for league in range(4):
 for entry in json.loads((ASSETS/f'teams-{league}.json').read_text())['sports'][0]['leagues'][0]['teams']:
  team=entry['team']
  if league==3 and team['id'] not in fbs:continue
  logos=team.get('logos',[])
  black=next((x for x in logos if 'primary_logo_black' in x.get('rel',[])),None)
  default=next((x for x in logos if 'default' in x.get('rel',[])),None)
  if black or default:jobs.append((league,team,[x['href'] for x in [black,default] if x]))
def convert(job):
 league,team,urls=job
 for url in urls:
  try:
   path=CACHE/f'{league}-{team["id"]}-{"black" if "primary_logo_black" in url else "color"}.png'
   if not path.exists():path.write_bytes(urllib.request.urlopen(url,timeout=25).read())
   im=Image.open(path).convert('RGBA');box=im.getchannel('A').getbbox()
   if box:im=im.crop(box)
   im.thumbnail((88,88),Image.Resampling.LANCZOS)
   bg=Image.new('RGBA',(96,96),'white');bg.alpha_composite(im,((96-im.width)//2,(96-im.height)//2))
   # Threshold rather than noisy halftones; preserve white interiors and alpha edges.
   gray=bg.convert('L');bw=gray.point(lambda p:255 if p>=205 else 0,mode='1')
   if bw.getextrema()!=(0,255):raise ValueError('blank logo')
   return league,team,url,bw
  except Exception as e:err=str(e)
 raise RuntimeError(f'{league}/{team["id"]} {team["displayName"]}: {err}')
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool: results=list(pool.map(convert,jobs))
results.sort(key=lambda x:(x[0],int(x[1]['id'])))
header=['// Generated by tools/build_logos.py. Team marks belong to their owners.','#pragma once','#include <stdint.h>','namespace retro {','struct TeamLogo { int league; const char* id; const uint8_t* bits; };']
manifest=[]
for league,team,url,bw in results:
 name=f'logo_{league}_{team["id"]}'
 data=ImageOps.invert(bw.convert('L')).convert('1').tobytes()
 header.append(f'static const uint8_t {name}[] = {{'+','.join(f'0x{b:02x}' for b in data)+'};')
 manifest.append({'league':league,'id':team['id'],'name':team['displayName'],'source':url})
header.append('static const TeamLogo teamLogos[] = {')
header.extend(f'{{{league},"{team["id"]}",logo_{league}_{team["id"]}}},' for league,team,_,_ in results)
header+=['};','inline const uint8_t* findLogo(int league,const std::string& id) { for(const auto& logo:teamLogos) if(logo.league==league && id==logo.id)return logo.bits;return nullptr;}','}']
(ROOT/'firmware/RetroSports/TeamLogos.h').write_text('\n'.join(header)+'\n')
(ASSETS/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(f'Bundled {len(results)} logos; FBS directory {len(fbs)} teams; {len(results)*1152:,} bitmap bytes.')
